### ISSUE TITLE
cache constructed indexes in sbot's leveldb

### ISSUE THREAD

**Issue by pfrazee** [ssbc/patchwork-api#2]
right now indexes are constructed and kept in memory, which can't work in the long run. we'll need to write out the indexes to leveldb (and update any of phoenix-api's sync methods to, sadly, all be async)

**Comment by dominictarr** [comment]
can you link me to the index code?

**Comment by pfrazee** [comment]
https://github.com/ssbc/phoenix-api/blob/master/indexer.js

**Comment by dominictarr** [comment]
if we moved some of this to the server we could process messages as they came in without instead of just requesting messages by type.

Also, I think you are using the term "index" incorrectly. An index is a way to look up another value (like a catalogue system in a library, or a search engine) but this is actually an aggregation of some subset of that data - I so the correct term for this is a "view".

A database "view", which is not related to the "view" in MVC.

**Comment by pfrazee** [comment]
> if we moved some of this to the server we could process messages as they came in without instead of just requesting messages by type.

true, we can move all of this into phoenix's server side

> Also, I think you are using the term "index" incorrectly. An index is a way to look up another value (like a catalogue system in a library, or a search engine) but this is actually an aggregation of some subset of that data - I so the correct term for this is a "view".

(in my defense) i think posts, posts by author, the inbox, and adverts qualify as indexes, but profiles, names, and threads are definitely views. i'm fine with generalizing them all as views

**Comment by dominictarr** [comment]
fair point.
